### ISSUE TITLE
bug: Fix the license inconsistency in the files

### ISSUE THREAD

**Issue by mayankjobanputra** [deepset-ai/canals#12]
Currently, in the majority of the files, I see these lines. @masci pointed out we should make it consistent with the actual license.

```
# SPDX-FileCopyrightText: 2023-present U.N. Owen <void@some.where>
#
# SPDX-License-Identifier: MIT
```

**Comment by ZanSara** [comment]
Fixed temporarily in https://github.com/deepset-ai/canals/pull/14, I wish there was a working pre-commit hook for this...

**Comment by mayankjobanputra** [comment]
The issue seems to be fixed, closing this :)
