### ISSUE TITLE
Add check that components sockets don't contain forbidden chars

### ISSUE THREAD

**Issue by silvanocerza** [deepset-ai/canals#75]
Since input sockets are meant to be passed as parameters to a component's `run` method they must be [valid Python identifiers](https://docs.python.org/3/reference/lexical_analysis.html#identifiers).

Similarly output sockets must be declared using the `@component.output_types(<socket_name>=<type>)` decorator so they must respect the same requirement.

We can leverage [`str.isidentifier()`](https://docs.python.org/3/library/stdtypes.html?highlight=identifier#str.isidentifier) and [`keyword.iskeyword(<string>)`](https://docs.python.org/3/library/keyword.html#keyword.iskeyword) to validate the socket name.

**Comment by ZanSara** [comment]
Let's not forget to add a note about this in the documentation
