### ISSUE TITLE
Restore original component names during pipeline unmarhsalling

### ISSUE THREAD

**Issue by ZanSara** [deepset-ai/canals#76]
Currently, if there happens to be two different components with the same name in a group of pipelines that are serialized together, such components' name will be different after marshalling, and unmarshalling will not restore the original names.

For example:

```python
pipeline_1 = Pipeline()
pipeline_1.add_component("add", AddFixedValue(add=200))
pipeline_1.add_component("double", Double())
pipeline_1.connect("add", "double")

pipeline_2 = Pipeline()
pipeline_2.add_component("add", AddFixedValue(add=100))
pipeline_2.add_component("duplicate", Double())
pipeline_2.connect("add", "double")

data = marshal_pipelines({"query": pipeline_1, "indexing": pipeline_2})
pipelines = unmarshal_pipelines(data)

# The components of `query` are now `add_1` and `double` (`add` changed name)
# The components of `indexing` are now `add_2` and `double` (`add` changed name)
```

Fixing this issue implies putting additional constraints on the component name, for example a forbidden character that could be used as a separator. If this is enforced, then it will be possible to create suffixes that can be removed while unmarshalling.

**Comment by silvanocerza** [comment]
Closing as this is not relevant anymore after #102.
